wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1683832213.316641
    t:
      1:
      - 55
      - 86
      2:
      - 55
      - 86
      3:
      - 23
      - 52
      4: 3.9.13
      5: 0.15.2
      8:
      - 1
      - 4
      - 5
